export const LAST_OPEN_FILE = 'LAST_OPEN_FILE'
export const IS_SHOW_BORDER = 'IS_SHOW_BORDER'
export const IS_ALLOW_DEFAULT_BEHAVIOR = 'IS_ALLOW_DEFAULT_BEHAVIOR'
export const sessionCachingKey = [
    LAST_OPEN_FILE, IS_SHOW_BORDER
]