export enum DATA_TYPE {
  TABLE = "TABLE",
  INPUT = "INPUT",
  INPUT_NUMBER = "INPUT_NUMBER",
  RICH_TEXT = "RICH_TEXT",
  CHECK_BOX = "CHECK_BOX",
  RADIO = "RADIO",
  DROP_DOWN = "DROP_DOWN",
  DATE_PICKER = "DATE_PICKER",
  RANGE_PICKER = "RANGE_PICKER",
  SWITCH = "SWITCH",
  COLOR_PICKER = "COLOR_PICKER",
  RATE = "RATE",
  UPLOAD = "UPLOAD",
  IMAGE = "IMAGE",
  TREE = "TREE",
}

export enum LAYOUT_TYPE {
  PANEL = "PANEL",
}

export enum CONTROL_TYPE {
  BUTTON = "BUTTON",
}

export type TYPE_DROP = CONTROL_TYPE | LAYOUT_TYPE | DATA_TYPE;
