export enum DATA_TYPE {
  TABLE = "TABLE",
  INPUT = "INPUT",
  INPUT_NUMBER = "INPUT_NUMBER",
  RICH_TEXT = "RICH_TEXT",
  CHECK_BOX = "CHECK_BOX",
  RADIO = "RADIO",
  DROP_DOWN = "DROP_DOWN",
  DATE_PICKER = "DATE_PICKER",
  RANGE_PICKER = "RANGE_PICKER",
  SWITCH = "SWITCH",
  COLOR_PICKER = "COLOR_PICKER",
  RATE = "RATE",
  UPLOAD = "UPLOAD",
  IMAGE = "IMAGE",
  TREE = "TREE",
  QR = "QR",
  CHART = "CHART",
}

export enum GENERAL_TYPE {
  PANEL = "PANEL",
  ROW = "ROW",
  COL = "COL",
  BUTTON = "BUTTON",
  TAB = "TAB",
}

export type TYPE_DROP = GENERAL_TYPE | DATA_TYPE;

export const DATA_COMPONENT_KEYS = [
  DATA_TYPE.TABLE,
  DATA_TYPE.INPUT,
  DATA_TYPE.INPUT_NUMBER,
  DATA_TYPE.RICH_TEXT,
  DATA_TYPE.CHECK_BOX,
  DATA_TYPE.RADIO,
  DATA_TYPE.DROP_DOWN,
  DATA_TYPE.DATE_PICKER,
  DATA_TYPE.RANGE_PICKER,
  DATA_TYPE.SWITCH,
  DATA_TYPE.COLOR_PICKER,
  DATA_TYPE.RATE,
  DATA_TYPE.UPLOAD,
  DATA_TYPE.IMAGE,
  DATA_TYPE.TREE,
  DATA_TYPE.QR,
  DATA_TYPE.CHART,
];

export const GENERAL_COMPONENT_KEYS = [
  GENERAL_TYPE.PANEL,
  GENERAL_TYPE.ROW,
  GENERAL_TYPE.BUTTON,
  GENERAL_TYPE.TAB,
];
